### ISSUE TITLE
[BUG] Chibisafe throws Server Error

### ISSUE THREAD

**Issue by fistwho** [chibisafe/chibisafe#323]
I used your Dockerfile to build a local docker image. I dont need the nginx part because i use the linuserver/swag nginx for my setup. So i build the image and got some Warnings. The Image seems to start and chibisafe should running. 

if i try to open it on my subdomain, i got the following error 

```
Server error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.
```

Docker Logs says: 
```
Backend ready and listening on port 5000

Error occurred when calling nuxtServerInit:  Request failed with status code 403


 ERROR  Request failed with status code 403


  at createError (node_modules/axios/lib/core/createError.js:16:15)

  at settle (node_modules/axios/lib/core/settle.js:17:12)

  at Unzip.handleStreamEnd (node_modules/axios/lib/adapters/http.js:260:11)

  at Unzip.emit (events.js:400:28)

  at Unzip.emit (domain.js:475:12)

  at endReadableNT (internal/streams/readable.js:1334:12)

  at processTicksAndRejections (internal/process/task_queues.js:82:21)

```
The nginx config looks like this:
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name safe.xxxxx.net;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 10.10.10.99;
        set $upstream_port 5000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}
```

And my Env's looks like this:
```
OVERWRITE_SETTINGS=false
CHUNK_SIZE=90
ROUTE_PREFIX=/api
RATE_LIMIT_WINDOW=2
RATE_LIMIT_MAX=5
BLOCKED_EXTENSIONS=.jar,.exe,.msi,.com,.bat,.cmd,.scr,.ps1,.sh
SECRET=*****************************************
MAX_LINKS_PER_ALBUM=5
META_THEME_COLOR=#20222b
META_DESCRIPTION=XxXxXxX - Blazing fast file bunker! 🚀
META_KEYWORDS=XxXxXxX
SERVER_PORT=5000
DOMAIN=http://safe.xxxxxxxxx.net
SERVICE_NAME=XxXxXxX
MAX_SIZE=5000
GENERATE_THUMBNAILS=true
GENERATE_ZIPS=true
STRIP_EXIF=true
SERVE_WITH_NODE=true
GENERATED_FILENAME_LENGTH=6
GENERATED_ALBUM_LENGTH=4
PUBLIC_MODE=false
USER_ACCOUNTS=true
ADMIN_ACCOUNT=SomeUserName
ADMIN_PASSWORD=**************************
DB_CLIENT=sqlite3
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NODE_VERSION=14.19.0
YARN_VERSION=1.22.17
```

I dont know much about node so i need some help and adjustments to get it running.

<3 Thank you ;)

**FULL LOG:**
```
> chibisafe@4.0.2 migrate /usr/chibisafe

> knex migrate:latest


Already up to date


> chibisafe@4.0.2 seed /usr/chibisafe

> knex seed:run



=========================================================

==       admin account already exists, skipping.       ==

=========================================================

==    Run `pm2 start pm2.json` to start the service    ==

=========================================================


Ran 1 seed files


> chibisafe@4.0.2 start /usr/chibisafe

> npm run migrate && nuxt build && cross-env NODE_ENV=production node src/api/structures/Server



> chibisafe@4.0.2 migrate /usr/chibisafe

> knex migrate:latest


Already up to date

ℹ Production build

ℹ Bundling for server and client side

ℹ Target: server

✔ Builder initialized

✔ Nuxt files generated


 WARN  Browserslist: caniuse-lite is outdated. Please run:

npx browserslist@latest --update-db


Why you should do it regularly:

https://github.com/browserslist/browserslist#browsers-data-updating


ℹ Compiling Client

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.


Recommendation: math.div($value, 255) or calc($value / 255)


More info and automated migrator: https://sass-lang.com/d/slash-div


   ╷

70 │     $value: $value / 255

   │             ^^^^^^^^^^^^

   ╵

    node_modules/bulma/sass/utilities/functions.sass 70:13   colorLuminance()

    node_modules/bulma/sass/utilities/functions.sass 80:8    findColorInvert()

    src/site/assets/styles/_bulma_colors_extender.scss 7:20  @import

    src/site/assets/styles/style.scss 2:9                    @import

    src/site/layouts/default.vue 64:9                        root stylesheet


DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.


Recommendation: math.div($value + 0.055, 1.055) or calc(($value + 0.055) / 1.055)


More info and automated migrator: https://sass-lang.com/d/slash-div


   ╷

74 │       $value: ($value + .055) / 1.055

   │               ^^^^^^^^^^^^^^^^^^^^^^^

   ╵

    node_modules/bulma/sass/utilities/functions.sass 74:15   colorLuminance()

    node_modules/bulma/sass/utilities/functions.sass 80:8    findColorInvert()

    src/site/assets/styles/_bulma_colors_extender.scss 7:20  @import

    src/site/assets/styles/style.scss 2:9                    @import

    src/site/layouts/default.vue 64:9                        root stylesheet


DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.


Recommendation: math.div($value, 12.92) or calc($value / 12.92)


More info and automated migrator: https://sass-lang.com/d/slash-div


   ╷

72 │       $value: $value / 12.92

   │               ^^^^^^^^^^^^^^

   ╵

    node_modules/bulma/sass/utilities/functions.sass 72:15          colorLuminance()

    node_modules/bulma/sass/utilities/functions.sass 80:8           findColorInvert()

    node_modules/bulma/sass/utilities/derived-variables.sass 16:20  @import

    node_modules/bulma/sass/utilities/_all.sass 6:9                 @import

    src/site/assets/styles/style.scss 6:9                           @import

    src/site/layouts/default.vue 64:9                               root stylesheet


DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.


Recommendation: math.div(-1, 2) or calc(-1 / 2)


More info and automated migrator: https://sass-lang.com/d/slash-div


   ╷

76 │       +ltr-property("margin", calc(#{-1 / 2 * $button-padding-horizontal} - #{$button-border-width}), false)

   │                                      ^^^^^^

   ╵

    node_modules/bulma/sass/elements/button.sass 76:38  @import

    node_modules/bulma/sass/elements/_all.sass 5:9      @import

    node_modules/bulma/bulma.sass 5:9                   @import

    src/site/assets/styles/style.scss 16:9              @import

    src/site/layouts/default.vue 64:9                   root stylesheet


DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.


Recommendation: math.div($button-padding-horizontal, 4) or calc($button-padding-horizontal / 4)


More info and automated migrator: https://sass-lang.com/d/slash-div


   ╷

77 │       +ltr-property("margin", $button-padding-horizontal / 4)

   │                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   ╵

    node_modules/bulma/sass/elements/button.sass 77:31  @import

    node_modules/bulma/sass/elements/_all.sass 5:9      @import

    node_modules/bulma/bulma.sass 5:9                   @import

    src/site/assets/styles/style.scss 16:9              @import

    src/site/layouts/default.vue 64:9                   root stylesheet


WARNING: 37 repetitive deprecation warnings omitted.


✔ Client: Compiled successfully in 25.79s

ℹ Compiling Server

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.


Recommendation: math.div($value, 255) or calc($value / 255)


More info and automated migrator: https://sass-lang.com/d/slash-div


   ╷

70 │     $value: $value / 255

   │             ^^^^^^^^^^^^

   ╵

    node_modules/bulma/sass/utilities/functions.sass 70:13   colorLuminance()

    node_modules/bulma/sass/utilities/functions.sass 80:8    findColorInvert()

    src/site/assets/styles/_bulma_colors_extender.scss 7:20  @import

    src/site/assets/styles/style.scss 2:9                    @import

    src/site/layouts/default.vue 64:9                        root stylesheet


DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.


Recommendation: math.div($value + 0.055, 1.055) or calc(($value + 0.055) / 1.055)


More info and automated migrator: https://sass-lang.com/d/slash-div


   ╷

74 │       $value: ($value + .055) / 1.055

   │               ^^^^^^^^^^^^^^^^^^^^^^^

   ╵

    node_modules/bulma/sass/utilities/functions.sass 74:15   colorLuminance()

    node_modules/bulma/sass/utilities/functions.sass 80:8    findColorInvert()

    src/site/assets/styles/_bulma_colors_extender.scss 7:20  @import

    src/site/assets/styles/style.scss 2:9                    @import

    src/site/layouts/default.vue 64:9                        root stylesheet


DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.


Recommendation: math.div($value, 12.92) or calc($value / 12.92)


More info and automated migrator: https://sass-lang.com/d/slash-div


   ╷

72 │       $value: $value / 12.92

   │               ^^^^^^^^^^^^^^

   ╵

    node_modules/bulma/sass/utilities/functions.sass 72:15          colorLuminance()

    node_modules/bulma/sass/utilities/functions.sass 80:8           findColorInvert()

    node_modules/bulma/sass/utilities/derived-variables.sass 16:20  @import

    node_modules/bulma/sass/utilities/_all.sass 6:9                 @import

    src/site/assets/styles/style.scss 6:9                           @import

    src/site/layouts/default.vue 64:9                               root stylesheet


DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.


Recommendation: math.div(-1, 2) or calc(-1 / 2)


More info and automated migrator: https://sass-lang.com/d/slash-div


   ╷

76 │       +ltr-property("margin", calc(#{-1 / 2 * $button-padding-horizontal} - #{$button-border-width}), false)

   │                                      ^^^^^^

   ╵

    node_modules/bulma/sass/elements/button.sass 76:38  @import

    node_modules/bulma/sass/elements/_all.sass 5:9      @import

    node_modules/bulma/bulma.sass 5:9                   @import

    src/site/assets/styles/style.scss 16:9              @import

    src/site/layouts/default.vue 64:9                   root stylesheet


DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.


Recommendation: math.div($button-padding-horizontal, 4) or calc($button-padding-horizontal / 4)


More info and automated migrator: https://sass-lang.com/d/slash-div


   ╷

77 │       +ltr-property("margin", $button-padding-horizontal / 4)

   │                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   ╵

    node_modules/bulma/sass/elements/button.sass 77:31  @import

    node_modules/bulma/sass/elements/_all.sass 5:9      @import

    node_modules/bulma/bulma.sass 5:9                   @import

    src/site/assets/styles/style.scss 16:9              @import

    src/site/layouts/default.vue 64:9                   root stylesheet


WARNING: 37 repetitive deprecation warnings omitted.


✔ Server: Compiled successfully in 8.83s


Hash: fa84012f50ef16b233c3

Version: webpack 4.46.0

Time: 25789ms

Built at: 02/02/2022 6:07:17 PM

                                                                                                          Asset       Size  Chunks                                Chunk Names

                                                                                 ../server/client.manifest.json   33.9 KiB          [emitted]                     

                                                                                                     0155224.js   50.2 KiB      23  [emitted] [immutable]         vendors/pages/index

                                                                                                     048e880.js   6.42 KiB       5  [emitted] [immutable]         pages/a/_identifier

                                                                                                     0c9d795.js   5.83 KiB       7  [emitted] [immutable]         pages/dashboard/admin/file/_id

                                                                                                     269a95c.js   3.01 KiB      18  [emitted] [immutable]         pages/login

                                                                                                     2e30f75.js   20.8 KiB       0  [emitted] [immutable]         pages/a/_identifier/pages/dashboard/admin/user/_id/pages/dashboard/albums/_id/pages/dashboard/index

                                                                                                     30883af.js   4.07 KiB      14  [emitted] [immutable]         pages/dashboard/index

                                                                                                     3c5c78e.js   11.3 KiB       8  [emitted] [immutable]         pages/dashboard/admin/settings

                                                                                                     3f414f5.js   27.8 KiB       1  [emitted] [immutable]         vendors/pages/a/_identifier/pages/dashboard/admin/user/_id/pages/dashboard/albums/_id/pages/dashboard/index

                                                                                                     3f4bdba.js   9.07 KiB       9  [emitted] [immutable]         pages/dashboard/admin/statistics

                                                                                                     48523dd.js   2.89 KiB      16  [emitted] [immutable]         pages/faq

                                                                                                     665ea05.js   5.62 KiB      21  [emitted] [immutable]         runtime

                                                                                                     79ce550.js   18.5 KiB       2  [emitted] [immutable]         pages/dashboard/albums/_id/pages/dashboard/index

                                                                                                     7cd02b1.js   6.16 KiB      10  [emitted] [immutable]         pages/dashboard/admin/user/_id

                                                                                                     7ef9f8b.js   87.8 KiB       3  [emitted] [immutable]         app

                                                                                                     80cc466.js   6.99 KiB       6  [emitted] [immutable]         pages/dashboard/account

                                                                                                     92c8422.js  519 bytes      19  [emitted] [immutable]         pages/logout

                                                                                                     946061b.js   8.14 KiB      11  [emitted] [immutable]         pages/dashboard/admin/users

                                                                                                       LICENSES   1.07 KiB          [emitted]                     

                                                                                                app.b00a7a7.css    624 KiB       3  [emitted] [immutable]  [big]  app

                                                                                                     beec9c8.js   2.96 KiB      20  [emitted] [immutable]         pages/register

                                                                                                     c42f890.js    191 KiB       4  [emitted] [immutable]         commons/app

                                                                                                     c4e04c7.js   10.7 KiB      17  [emitted] [immutable]         pages/index

                                                                                                     dbee12e.js   18.7 KiB      13  [emitted] [immutable]         pages/dashboard/albums/index

                                                                                                     f15883c.js    307 KiB      22  [emitted] [immutable]  [big]  vendors/app

                                                                                                     f253a87.js   4.09 KiB      12  [emitted] [immutable]         pages/dashboard/albums/_id

                                                                                                     f964b62.js   6.58 KiB      15  [emitted] [immutable]         pages/dashboard/tags/index

                                                                  fonts/materialdesignicons-webfont.3d1f8fa.eot    982 KiB          [emitted]              [big]  

                                                                  fonts/materialdesignicons-webfont.3e722fd.ttf    981 KiB          [emitted]              [big]  

                                                                fonts/materialdesignicons-webfont.4187121.woff2    312 KiB          [emitted]              [big]  

                                                                 fonts/materialdesignicons-webfont.fec1b66.woff    446 KiB          [emitted]              [big]  

                                                                                     img/background.4a227cd.jpg   73.7 KiB          [emitted]                     

                                                                                          img/blank.daa9806.png   1.44 KiB          [emitted]                     

                                                                                           img/logo.a61651d.png     11 KiB          [emitted]                     

                                                                                pages/a/_identifier.c6aaeb9.css  548 bytes       5  [emitted] [immutable]         pages/a/_identifier

pages/a/_identifier/pages/dashboard/admin/user/_id/pages/dashboard/albums/_id/pages/dashboard/index.8a817a7.css   3.09 KiB       0  [emitted] [immutable]         pages/a/_identifier/pages/dashboard/admin/user/_id/pages/dashboard/albums/_id/pages/dashboard/index

                                                                            pages/dashboard/account.53158bf.css  257 bytes       6  [emitted] [immutable]         pages/dashboard/account

                                                                     pages/dashboard/admin/file/_id.c3991d3.css  311 bytes       7  [emitted] [immutable]         pages/dashboard/admin/file/_id

                                                                     pages/dashboard/admin/settings.a0fa9f4.css  814 bytes       8  [emitted] [immutable]         pages/dashboard/admin/settings

                                                                   pages/dashboard/admin/statistics.40b9093.css  571 bytes       9  [emitted] [immutable]         pages/dashboard/admin/statistics

                                                                     pages/dashboard/admin/user/_id.aee17cc.css  311 bytes      10  [emitted] [immutable]         pages/dashboard/admin/user/_id

                                                                        pages/dashboard/admin/users.60e0839.css    2.3 KiB      11  [emitted] [immutable]         pages/dashboard/admin/users

                                                                         pages/dashboard/albums/_id.2bd807b.css  295 bytes      12  [emitted] [immutable]         pages/dashboard/albums/_id

                                                   pages/dashboard/albums/_id/pages/dashboard/index.5b39451.css  325 bytes       2  [emitted] [immutable]         pages/dashboard/albums/_id/pages/dashboard/index

                                                                       pages/dashboard/albums/index.cb9f048.css   2.74 KiB      13  [emitted] [immutable]         pages/dashboard/albums/index

                                                                              pages/dashboard/index.93736b0.css  189 bytes      14  [emitted] [immutable]         pages/dashboard/index

                                                                         pages/dashboard/tags/index.3cfa1dd.css    2.2 KiB      15  [emitted] [immutable]         pages/dashboard/tags/index

                                                                                          pages/faq.e32dd9b.css   55 bytes      16  [emitted] [immutable]         pages/faq

                                                                                        pages/index.f426ced.css   12.1 KiB      17  [emitted] [immutable]         pages/index

 + 2 hidden assets

Entrypoint app [big] = 665ea05.js c42f890.js f15883c.js app.b00a7a7.css 7ef9f8b.js


WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).

This can impact web performance.

Assets: 

  fonts/materialdesignicons-webfont.4187121.woff2 (312 KiB)

  fonts/materialdesignicons-webfont.fec1b66.woff (446 KiB)

  fonts/materialdesignicons-webfont.3d1f8fa.eot (982 KiB)

  fonts/materialdesignicons-webfont.3e722fd.ttf (981 KiB)

  app.b00a7a7.css (624 KiB)

  f15883c.js (307 KiB)


WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (1000 KiB). This can impact web performance.
      
Entrypoints:

  app (1.19 MiB)

      665ea05.js

      c42f890.js

      f15883c.js

      app.b00a7a7.css

      7ef9f8b.js



Hash: 12b4cd985cf59265d8e3

Version: webpack 4.46.0

Time: 8829ms

Built at: 02/02/2022 6:07:26 PM

                              Asset      Size  Chunks             Chunk Names

             pages/a/_identifier.js  52.9 KiB       1  [emitted]  pages/a/_identifier

         pages/dashboard/account.js  12.6 KiB       2  [emitted]  pages/dashboard/account

  pages/dashboard/admin/file/_id.js  15.1 KiB       3  [emitted]  pages/dashboard/admin/file/_id

  pages/dashboard/admin/settings.js  21.7 KiB       4  [emitted]  pages/dashboard/admin/settings

pages/dashboard/admin/statistics.js  26.7 KiB       5  [emitted]  pages/dashboard/admin/statistics

  pages/dashboard/admin/user/_id.js  54.1 KiB       6  [emitted]  pages/dashboard/admin/user/_id

     pages/dashboard/admin/users.js    17 KiB       7  [emitted]  pages/dashboard/admin/users

      pages/dashboard/albums/_id.js  99.9 KiB       8  [emitted]  pages/dashboard/albums/_id

    pages/dashboard/albums/index.js  35.2 KiB       9  [emitted]  pages/dashboard/albums/index

           pages/dashboard/index.js  97.1 KiB      10  [emitted]  pages/dashboard/index

      pages/dashboard/tags/index.js  16.7 KiB      11  [emitted]  pages/dashboard/tags/index

                       pages/faq.js  6.73 KiB      12  [emitted]  pages/faq

                     pages/index.js  28.3 KiB      13  [emitted]  pages/index

                     pages/login.js  5.36 KiB      14  [emitted]  pages/login

                    pages/logout.js  1.27 KiB      15  [emitted]  pages/logout

                  pages/register.js  4.74 KiB      16  [emitted]  pages/register

                          server.js   138 KiB       0  [emitted]  app

               server.manifest.json  2.11 KiB          [emitted]  

 + 17 hidden assets

Entrypoint app = server.js server.js.map

ℹ Ready to run nuxt start


   ╭──────────────────────────────────────────────────────────────────────────────────────╮

   │                                                                                      │

   │   ⚠ Nuxt Warning                                                                     │

   │                                                                                      │

   │   The command 'nuxt build' finished but did not exit after 5s                        │

   │   This is most likely not caused by a bug in Nuxt                                    │

   │   Make sure to cleanup all timers and listeners you or your plugins/modules start.   │

   │   Nuxt will now force exit                                                           │

   │                                                                                      │

   │   DeprecationWarning: Starting with Nuxt version 3 this will be a fatal error        │

   │                                                                                      │

   ╰──────────────────────────────────────────────────────────────────────────────────────╯


Found route POST /api/admin/ban/ip

Found route GET /api/admin/file/:id

Found route POST /api/admin/unban/ip

Found route POST /api/admin/users/demote

Found route POST /api/admin/users/disable

Found route POST /api/admin/users/enable

Found route GET /api/admin/users/:id

Found route POST /api/admin/users/promote

Found route POST /api/admin/users/purge

Found route GET /api/admin/users

Found route DELETE /api/album/:id

Found route POST /api/album/edit

Found route GET /api/album/:id/full

Found route GET /api/album/:identifier

Found route POST /api/album/new

Found route DELETE /api/album/:id/purge

Found route GET /api/album/:identifier/zip

Found route GET /api/albums/mini

Found route GET /api/albums/dropdown

Found route DELETE /api/album/link/delete/:identifier

Found route POST /api/album/link/edit

Found route POST /api/album/link/new

Found route GET /api/album/:id/links

Found route POST /api/auth/login

Found route POST /api/auth/register

Found route POST /api/file/album/add

Found route POST /api/file/album/del

Found route DELETE /api/file/:id

Found route GET /api/file/:id

Found route GET /api/file/:id/albums

Found route GET /api/files

Found route POST /api/file/tag/addBatch

Found route POST /api/file/tag/add

Found route POST /api/file/tag/del

Found route GET /api/search/

Found route GET /api/service/config/all

Found route GET /api/service/config

Found route POST /api/service/config

Found route GET /api/service/config/schema

Found route POST /api/service/restart

Found route GET /api/service/statistics/:category?

Found route GET /api/version

Found route DELETE /api/tag/:id/:purge?

Found route POST /api/tag/new

Found route GET /api/tags

Found route POST /api/upload

Found route POST /api/user/apikey/change

Found route POST /api/user/password/change

Found route GET /api/users/me

Found route GET /api/verify

Backend ready and listening on port 5000

Error occurred when calling nuxtServerInit:  Request failed with status code 403


 ERROR  Request failed with status code 403


  at createError (node_modules/axios/lib/core/createError.js:16:15)

  at settle (node_modules/axios/lib/core/settle.js:17:12)

  at Unzip.handleStreamEnd (node_modules/axios/lib/adapters/http.js:260:11)

  at Unzip.emit (events.js:400:28)

  at Unzip.emit (domain.js:475:12)

  at endReadableNT (internal/streams/readable.js:1334:12)

  at processTicksAndRejections (internal/process/task_queues.js:82:21)

```

**Comment by Aareksio** [comment]
Dart Sass deprecation warnings shouldn't result in Nuxt's "Service Error" page.

> Error occurred when calling nuxtServerInit:  Request failed with status code 403

I see only one `nuxtServerInit` in store, and it does 2 requests:
- `GET /service/config`
- `GET /auth/verify`

The 2nd call is wrapped in try...catch so shouldn't throw
The 1st one shouldn't return 403 according to `{ bypassAuth: true }` and `Route` implementation

No part of the related code have been modified in at least 5 months, it is strange no one reported the issue before. Are there any major changes in your custom config compared to the default one?

**Comment by KeinNerd** [comment]
sorry for the late response, i dont change anything on the config or dockerfile. i only use the ENV's

**Comment by Minecodes** [comment]
I had the same problem today. I hope it will be fixed soon. But I have the problem outside of docker.

**Comment by dudefoxlive** [comment]
This is happening to me as well. I don't use docker and get this error.

**Comment by Pitu** [comment]
I'm closing this since the new version was just pushed to master.
