### ISSUE TITLE
[BUG] iOS shortcut doesn't work with network storage

### ISSUE THREAD

**Issue by nowakjestem** [chibisafe/chibisafe#678]
**Describe the bug**
When uploading file using [iOS shortcut](https://www.icloud.com/shortcuts/a63987ea47204bbba24d063d620fcf94) to instance with enabled network storage I get following error
```
{"level":50,"time":1720367144412,"pid":148,"err":{"type":"TypeError","message":"Cannot destructure property 'contentType' of 'req.body' as it is undefined.","stack":"TypeError: Cannot destructure property 'contentType' of 'req.body' as it is undefined.\n    at uploadToNetworkStorage (file:///app/packages/backend/dist/routes/files/Upload.js:66:13)\n    at Module.run (file:///app/packages/backend/dist/routes/files/Upload.js:117:16)\n    at Object.handler (file:///app/packages/backend/dist/structures/routes.js:111:50)\n    at preHandlerCallback (/app/node_modules/fastify/lib/handleRequest.js:137:37)\n    at next (/app/node_modules/fastify/lib/hooks.js:233:9)\n    at Module.default (file:///app/packages/backend/dist/middlewares/auth.js:7:9)\n    at Object.<anonymous> (file:///app/packages/backend/dist/structures/routes.js:88:92)\n    at hookIterator (/app/node_modules/fastify/lib/hooks.js:405:10)\n    at next (/app/node_modules/fastify/lib/hooks.js:239:18)\n    at handleResolve (/app/node_modules/fastify/lib/hooks.js:250:7)"},"msg":"Cannot destructure property 'contentType' of 'req.body' as it is undefined."}
```
Everything works as expected when network storage is disabled. 

**To Reproduce**
1. Enable network storage
2. Add a file using iOS shortcut

**Expected behavior**
File is uploaded

**Additional context**
This shortcut uses Multipart-Form as it's only way to upload a file using shortcuts. I think this may be a problem as request is handled differently.

**Comment by Pitu** [comment]
The iOS shortcut doesn't support uploading with network storage for the time being since it needs to make several requests for that.
